# Generated by Django 3.1.2 on 2020-10-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
