# Generated by Django 3.1.2 on 2020-10-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='product_name',
            new_name='picture_name',
        ),
    ]
