# Generated by Django 3.1.2 on 2020-10-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20201014_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
