# Generated by Django 3.1.2 on 2020-10-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0007_auto_20201016_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='datetime',
        ),
    ]
