# Generated by Django 3.1.2 on 2020-10-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0012_auto_20201017_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
