# Generated by Django 3.1.2 on 2020-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0013_delete_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
