# Generated by Django 3.1.2 on 2020-10-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0017_auto_20201018_2140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='TeamMember',
        ),
    ]
