# Generated by Django 3.1.2 on 2020-10-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0018_auto_20201018_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.CharField(default='Adarsh Pandey', max_length=30),
        ),
    ]
